/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Classes.Endereco;
import Classes.Faturas;
import Classes.Tarifas;
import ConexaoBD.FaturasBD;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class MenuMedidor extends javax.swing.JFrame {

    /**
     * Creates new form MenuMedidor
     */
    public MenuMedidor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    FaturasBD faturasBD = new FaturasBD();
    Endereco endereco = new Endereco();
    Tarifas tarifa = new Tarifas();
    Faturas fatura = new Faturas();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuSuperior = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnColeta = new javax.swing.JButton();
        Principal = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Coleta = new javax.swing.JPanel();
        jtfCEP = new javax.swing.JTextField();
        jtfNumero = new javax.swing.JTextField();
        jtfKwGastos = new javax.swing.JTextField();
        CampoCEP = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CampoKwh = new javax.swing.JLabel();
        CampoBandeira1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnSalvar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MenuSuperior.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo CPFL.png"))); // NOI18N

        Menu.setBackground(new java.awt.Color(0, 152, 209));
        Menu.setLayout(null);

        btnInicio.setBackground(new java.awt.Color(0, 152, 209));
        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconInicio.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(null);
        btnInicio.setBorderPainted(false);
        btnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicio.setFocusPainted(false);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        Menu.add(btnInicio);
        btnInicio.setBounds(0, 0, 180, 40);

        btnSair.setBackground(new java.awt.Color(0, 152, 209));
        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconSair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setFocusPainted(false);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        Menu.add(btnSair);
        btnSair.setBounds(1280, 0, 100, 40);

        btnColeta.setBackground(new java.awt.Color(0, 152, 209));
        btnColeta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnColeta.setForeground(new java.awt.Color(255, 255, 255));
        btnColeta.setText("Coleta");
        btnColeta.setBorder(null);
        btnColeta.setBorderPainted(false);
        btnColeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColeta.setFocusPainted(false);
        btnColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColetaActionPerformed(evt);
            }
        });
        Menu.add(btnColeta);
        btnColeta.setBounds(180, 0, 180, 40);

        javax.swing.GroupLayout MenuSuperiorLayout = new javax.swing.GroupLayout(MenuSuperior);
        MenuSuperior.setLayout(MenuSuperiorLayout);
        MenuSuperiorLayout.setHorizontalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSuperiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuSuperiorLayout.setVerticalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSuperiorLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Principal.setBackground(new java.awt.Color(255, 255, 255));
        Principal.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Principal.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Principal.png"))); // NOI18N

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1384, Short.MAX_VALUE)
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        Principal.add(Inicio, "inicio");

        Coleta.setBackground(new java.awt.Color(255, 255, 255));
        Coleta.setLayout(null);

        jtfCEP.setBackground(new java.awt.Color(235, 235, 235));
        jtfCEP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfCEP.setBorder(null);
        Coleta.add(jtfCEP);
        jtfCEP.setBounds(325, 95, 260, 20);

        jtfNumero.setBackground(new java.awt.Color(235, 235, 235));
        jtfNumero.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfNumero.setBorder(null);
        Coleta.add(jtfNumero);
        jtfNumero.setBounds(640, 100, 50, 20);

        jtfKwGastos.setBackground(new java.awt.Color(235, 235, 235));
        jtfKwGastos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtfKwGastos.setBorder(null);
        Coleta.add(jtfKwGastos);
        jtfKwGastos.setBounds(320, 200, 270, 20);

        CampoCEP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/campo.png"))); // NOI18N
        Coleta.add(CampoCEP);
        CampoCEP.setBounds(310, 90, 300, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 152, 209));
        jLabel14.setText("CEP:");
        Coleta.add(jLabel14);
        jLabel14.setBounds(320, 70, 100, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 152, 209));
        jLabel15.setText("KW gastos:");
        Coleta.add(jLabel15);
        jLabel15.setBounds(320, 160, 100, 20);

        CampoKwh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/campo.png"))); // NOI18N
        Coleta.add(CampoKwh);
        CampoKwh.setBounds(310, 190, 300, 40);

        CampoBandeira1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/campoPequeno.png"))); // NOI18N
        Coleta.add(CampoBandeira1);
        CampoBandeira1.setBounds(630, 90, 80, 40);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 152, 209));
        jLabel26.setText("Nº:");
        Coleta.add(jLabel26);
        jLabel26.setBounds(630, 70, 100, 20);

        btnSalvar1.setBackground(new java.awt.Color(0, 152, 209));
        btnSalvar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalvar1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconSalvar.png"))); // NOI18N
        btnSalvar1.setText("Salvar");
        btnSalvar1.setBorder(null);
        btnSalvar1.setBorderPainted(false);
        btnSalvar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalvar1.setFocusPainted(false);
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });
        Coleta.add(btnSalvar1);
        btnSalvar1.setBounds(330, 290, 110, 40);

        btnCancelar1.setBackground(new java.awt.Color(0, 152, 209));
        btnCancelar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconCancelar.png"))); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorder(null);
        btnCancelar1.setBorderPainted(false);
        btnCancelar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar1.setFocusPainted(false);
        Coleta.add(btnCancelar1);
        btnCancelar1.setBounds(500, 290, 110, 40);

        Principal.add(Coleta, "coleta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(MenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "inicio");
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColetaActionPerformed
        CardLayout cl = (CardLayout) Principal.getLayout();
        cl.show(Principal, "coleta");
    }//GEN-LAST:event_btnColetaActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        endereco.setCep(jtfCEP.getText());
        endereco.setNum_casa(Integer.parseInt(jtfNumero.getText()));
        fatura.setKwGastos(Double.parseDouble(jtfKwGastos.getText()));

        try {
            int idUser = faturasBD.verificarEndereco(endereco);

            if (idUser > 0) {
                int opcao = JOptionPane.showConfirmDialog(this, "Os dados estão corretos? \n" + "\n - CEP: " + jtfCEP.getText()
                        + "  Nº: " + jtfNumero.getText() + "\n- Kw Gastos pela residencia: " + jtfKwGastos.getText());

                if (opcao == 0) {
                    faturasBD.inserir(fatura, idUser);
                    JOptionPane.showMessageDialog(null, "Dados cadastrados com Sucesso!!");
                    limparCampos();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Endereço não encontrado!!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar dados.\n" + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void limparCampos() {
        jtfCEP.setText("");
        jtfKwGastos.setText("");
        jtfNumero.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CampoBandeira1;
    private javax.swing.JLabel CampoCEP;
    private javax.swing.JLabel CampoKwh;
    private javax.swing.JPanel Coleta;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel MenuSuperior;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnColeta;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCEP;
    private javax.swing.JTextField jtfKwGastos;
    private javax.swing.JTextField jtfNumero;
    // End of variables declaration//GEN-END:variables
}
